apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo-depo
 namespace: default
 labels:
   app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo-pod
      namespace: default
      labels:
        app: demo
    spec:
      containers:
      - name: sync-demo
        image: busybox
        command:
        - sleep
        - "3600"
#        imagePullPolicy: Never
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
        - name: foo
          configMap:
            name: demo-config
